name: txt-zoom

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    env: 
      DATABASE_URL: postgresql://nnoxflfmtenoyl:98f6674df5e52d0bf7dbe8a8286c9af1c0a04d7c2dd71d5041eb322398e4b462@ec2-54-170-123-247.eu-west-1.compute.amazonaws.com:5432/d6079umsufped9
      JWT_SECRET: 18EFA4F8661B07D25182B477686BD028FEBFF008A6D6F99C4D521DEE9F1F83B7
      

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn build 
    # migrate database
    - run: yarn run migrate:up
    - run: yarn test