name: t-zoom

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    env: 
      DATABASE_URL: postgresql://nnoxflfmtenoyl:98f6674df5e52d0bf7dbe8a8286c9af1c0a04d7c2dd71d5041eb322398e4b462@ec2-54-170-123-247.eu-west-1.compute.amazonaws.com:5432/d6079umsufped9

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build --if-present
    # migrate database
    - run: npm run migrate:up
    - run: npm test
      env:
        CI: true