name: t-zoom

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    # prisma enviroment variables
    env: 
      DATABASE_URL: postgresql://nnoxflfmtenoyl:98f6674df5e52d0bf7dbe8a8286c9af1c0a04d7c2dd71d5041eb322398e4b462@ec2-54-170-123-247.eu-west-1.compute.amazonaws.com:5432/d6079umsufped9

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    # migrate database
    - run: npm run migrate:up
    - run: npm run test
      env:
        CI: true